### ISSUE TITLE
Http Bytes compatibility

### ISSUE THREAD

**Issue by andrewMacmurray** [andrewMacmurray/elm-concurrent-task#16]
It would be nice to make the `ConcurrentTask.Http` module compatible with `elm/bytes`.

A popular way seems to be encoding / decoding a Base64 string with a [package like this](https://package.elm-lang.org/packages/danfishgold/base64-bytes/latest/). This however loses most of performance gains of using `Bytes`.

I'd be curious if anyone has any opinions / alternatives to this.

**Comment by dillonkearns** [comment]
I don't think there's a way to avoid the Base64 workaround without hacks, except for using the Lamdera compiler which does allow for Bytes to be passed through ports directly.

**Comment by andrewMacmurray** [comment]
That's fair, I guess it's worth adding it for compatibility and then others can opt-in to hacks / lamdera if needed
