### ISSUE TITLE
ConcurrentTask.Time.getZoneName references wrong js function

### ISSUE THREAD

**Issue by lue-bird** [andrewMacmurray/elm-concurrent-task#23]
https://github.com/andrewMacmurray/elm-concurrent-task/blob/1.0.0/src/ConcurrentTask/Time.elm#L86C29-L86C29
uses `builtin:timeZoneOffset` instead of `builtin:timeZoneName`.
This seems unintentional?

Just something I've noticed looking through the code, nothing that's bitten me. Much love for making this package :blue_heart:

**Comment by andrewMacmurray** [comment]
Ah well spotted! You're right that's unintentional.
