### ISSUE TITLE
implementation question about consuming JSON body

### ISSUE THREAD

**Issue by lue-bird** [andrewMacmurray/elm-concurrent-task#25]
For expect JSON, why does the http body get decoded with .text(). instead of [.json()](https://developer.mozilla.org/en-US/docs/Web/API/Request/json)
https://github.com/andrewMacmurray/elm-concurrent-task/blob/1.0.0/runner/http/fetch.ts#L30?

Just something I've noticed looking over the code. Is this intentional?

**Comment by andrewMacmurray** [comment]
Hey hey, yea that one is expected, I should add a comment to explain it as it looks odd at first glance.

`response.json()` effectively does a `response.text()` + `JSON.parse`. If `JSON.parse` throws an error you have to handle an extra case in elm for malformed json (which is already handled by `Json.Decode.decodeString` / `Json.Decode.decodeValue`).

**Comment by lue-bird** [comment]
Oh, I see. It's this line that does the magic: https://github.com/andrewMacmurray/elm-concurrent-task/blob/main/src/ConcurrentTask/Http.elm#L341
