### ISSUE TITLE
Copy API from `Time`

### ISSUE THREAD

**Issue by miniBill** [andrewMacmurray/elm-concurrent-task#29]
How do you feel about the idea of copying the API from `elm/time` inside `ConcurrentTask.Time`?

The idea is that then you can `import ConcurrentTask.Time as Time` and just use it as if it were the normal `Time` module.

**Comment by andrewMacmurray** [comment]
What's your use case for it?

If I'm using one of the built in Tasks (from `Time`, `Browser.Dom`, `Random`) I usually use the fully qualified import so it doesn't clash with core elm one:

```elm
import ConcurrentTask exposing (ConcurrentTask)
import ConcurrentTask.Time
import Time


nowMillis : ConcurrentTask x Int
nowMillis =
    ConcurrentTask.Time.now
        |> ConcurrentTask.map Time.posixToMillis

```

**Comment by miniBill** [comment]
My use case is only importing `ConcurrentTask.Time` and not importing `Time` at all, but just going fully qualified is a reasonable option.
