### ISSUE TITLE
ConcurrentTask.debug does not work

### ISSUE THREAD

**Issue by ni-ko-o-kin** [andrewMacmurray/elm-concurrent-task#30]
debug does not print anything to the console. See: https://gist.github.com/ni-ko-o-kin/3c3bd1cccff863c78caa645e24e7970a line 39 and line 41

Steps to reproduce:

```
npm init --yes
npm install @andrewmacmurray/elm-concurrent-task

cd src
elm install elm/json
elm install andrewMacmurray/elm-concurrent-task

cd ..
elm make src/Main.elm --output elm.js
node main.js
```

**Comment by lue-bird** [comment]
I'd assume it's because the `debugLog` tasks are ignored internally

https://github.com/andrewMacmurray/elm-concurrent-task/blob/main/src/ConcurrentTask.elm#L691

which should probably be `|> map (\_ -> a)`

**Comment by andrewMacmurray** [comment]
Thanks for spotting this @ni-ko-o-kin, I'm not sure how I missed it but @lue-bird points out it's missing a `|> map` and similar for the error case - the full implementation should be something like:

```elm
debug : (a -> String) -> (x -> String) -> ConcurrentTask x a -> ConcurrentTask x a
debug toOk toErr task =
    task
        |> andThen
            (\a ->
                toOk a
                    |> debugLog "Success"
                    |> map (\_ -> a)
            )
        |> onError
            (\x ->
                toErr x
                    |> debugLog "Failure"
                    |> andThenDo (fail x)
            )

```

I'll make the fix and release a patch version.

**Comment by ni-ko-o-kin** [comment]
Thank you for the fast fix!
