### ISSUE TITLE
[feature] finallyDo

### ISSUE THREAD

**Issue by ni-ko-o-kin** [andrewMacmurray/elm-concurrent-task#33]
```
import ConcurrentTask as CT exposing (ConcurrentTask)

finallyDo : ConcurrentTask e a -> ConcurrentTask e b -> ConcurrentTask e a
finallyDo secondTask firstTask =
    firstTask
        |> CT.onError (\e -> secondTask |> CT.andThenDo (CT.fail e))
        |> CT.andThenDo secondTask

```
Similar to Javascripts try-catch-**finally** statement. For example, I'm using `finallyDo` to make sure `unlockResource` gets called in both, the success and failure case:

```
callInsideLock : ConcurrentTask e a -> ConcurrentTask e b
callInsideLock task =
    lockResource
        |> CT.andThenDo task
        |> CT.finallyDo unlockResource
```

instead of

```
callInsideLock : ConcurrentTask e a -> ConcurrentTask e b
callInsideLock task =
     lockResource
        |> CT.andThenDo (task |> CT.onError (\e -> CT.andThenDo (CT.fail e) unlockResource))
        |> CT.andThenDo unlockResource
```

Are you interested in adding this to elm-concurrent-task? I would open a PR if so.

**Comment by andrewMacmurray** [comment]
Sorry missed this - sure, that feels like it would fit sensibly in the [helpers section](https://package.elm-lang.org/packages/andrewMacmurray/elm-concurrent-task/latest/ConcurrentTask#convenience-helpers), feel free to make a PR.

**Comment by ni-ko-o-kin** [comment]
Thanks! WIP!

**Comment by ni-ko-o-kin** [comment]
see https://github.com/andrewMacmurray/elm-concurrent-task/pull/34
